### ISSUE TITLE
Кликабельный стикер в истории

### ISSUE THREAD

**Issue by SevereCloud** [SevereCloud/vksdk#66]
[Кликабельный стикер](https://vk.com/dev/objects/clickable_stickers)

### TODO:

- [x] Объект, описывающий кликабельный стикер
- [x] Кликабельный стикер в историях
- [x] Функции для создания кликабельных стикеров
- [x] Описать документацию для кликабельных стикеров
