### ISSUE TITLE
v2: Использование context для events

### ISSUE THREAD

**Issue by SevereCloud** [SevereCloud/vksdk#91]
Пакет [context](https://golang.org/pkg/context/) в Go полезен при взаимодействиях с API и медленными процессами. В данный момент context используется в **foaf**.

За изменениями можно наблюдать в ветке [v2/events](https://github.com/SevereCloud/vksdk/tree/v2/events)

### TODO:
 
- [x] все функции должны передавать `ctx context.Context`
- [x] модули, использующие **events**, должны передавать `ctx context.Context`
- [x] `groupID`, `eventID`, `ts` должны передаваться через контекст
- [x] Тесты контекстов
- [x] Обновление документации
- [x] Документация для миграции

Ссылки
- [Go Concurrency Patterns: Context - The Go Blog](https://blog.golang.org/context)
- [Godoc](https://golang.org/pkg/context/)
