### ISSUE TITLE
v2: Переработка ошибок для api

### ISSUE THREAD

**Issue by SevereCloud** [SevereCloud/vksdk#99]
# TODO:

- [x] Удалить `object.Error`, заменить на `api.Error`
- [x] Отказаться от [github.com/pkg/errors](https://github.com/pkg/errors) в пользу стандартных ошибок
- [x] Перенести все ошибки из `api/errors` в `api` (создать отдельный файл errors.go)

Код ошибки

```go
// ErrorType is the type of an error
type ErrorType int

// Error returns the mssage of a ErrorType
func (e ErrorType) Error() string {
	return fmt.Spritf("api: error with code %d", e)
}

// Error codes. See https://vk.com/dev/errors
const (
	// Тут огромный список
)
```

Ошибка

```go
type Error struct {
	Code             int                `json:"error_code"`
	Message          string             `json:"error_msg"`
	Text             string             `json:"error_text"`
	CaptchaSID       string             `json:"captcha_sid"`
	CaptchaImg       string             `json:"captcha_img"`
	ConfirmationText string             `json:"confirmation_text"`
	RequestParams    []BaseRequestParam `json:"request_params"`
}

func (e Error) Error() string {
	return fmt.Spritf("api: %s", e.Message)
}
```

- [x] Сделать префикс для кодов ошибок `Err`
- [x] Поддержка `errors.Is` и `errors.As` из [1.13](https://blog.golang.org/go1.13-errors) 

Необходимо добавить

```go
func (e Error) Is(target error) bool {
	if t, ok := target.(*Error); ok {
		return e.Code == t.Code && e.Message == t.Message
	}

	if t, ok := target.(*ErrorType); ok {
		return e.Code == int(t)
	}

	return false
}

func (e Error) As(target error) bool {
	if t, ok := target.(*Error); ok {
		return e.Code == t.Code
	}

	if t, ok := target.(*ErrorType); ok {
		return e.Code == int(t)
	}

	return false
}
```

Теперь можно делать так

```go
if errors.Is(err, api.ErrAuth) {
	// ошибка авторизации
}
```

- [x] Добавить новый тип ошибки для execute

```go
type ExecuteErrors []Error

func (e ExecuteErrors) Error() string {
	return fmt.Spritf("api: execute errors (%d)", len(e))
}
```

- [x] Создать общую ошибку для Upload методов

Как? Я еще не придумал

- [x] Документация для миграции

### По мелочам

- [ ] Добавить `api.Error` метод для получения `api.Params` из поля `RequestParams`
